---
Parameters:
  SourceBucketName:
    Description: Enter source bucket name
    Type: String

  DestinationBucketName:
    Description: Enter destination bucket name
    Type: String

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket 
    Properties:
      BucketName: !Ref SourceBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt LambdaFunctionForS3event.Arn 

  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionForS3event
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::${SourceBucketName}'

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName

    
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucketName}/*
                  - !Sub arn:aws:s3:::${DestinationBucketName}/*
      
      Description: lambda execuation role policies

  LambdaFunctionForS3event:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Description: Lambda function that triggers on S3 object creation event in the
        source bucket and copies the object to the destination bucket.
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Environment: 
        Variables:
          "SourceBucketName": !Ref SourceBucketName
          "DestinationBucketName": !Ref DestinationBucketName
      Code:
        S3Bucket: lambda-code-bucket789
        S3Key: lambda-code.zip